# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedplace',
            name='users_voted',
            field=models.ManyToManyField(related_name='place', to=settings.AUTH_USER_MODEL),
        ),
    ]
