# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 04:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysessions', '0003_auto_20180114_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vote', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='users',
        ),
        migrations.AlterField(
            model_name='selectedplace',
            name='nbr_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
        migrations.AddField(
            model_name='vote',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysessions.SelectedPlace'),
        ),
        migrations.AddField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysessions.Session'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'session', 'place')]),
        ),
    ]
