# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysessions', '0005_auto_20180117_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user_vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(default=b'none', max_length=4),
        ),
        migrations.AlterField(
            model_name='vote',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_votes', to='mysessions.SelectedPlace'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_votes', to='mysessions.Session'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
