# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysessions', '0008_auto_20180119_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_type',
            new_name='vote_value',
        ),
    ]
