# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysessions', '0007_auto_20180119_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedplace',
            old_name='votes',
            new_name='nbr_votes',
        ),
    ]
